### ISSUE TITLE
Issue rendering

### ISSUE THREAD

**Issue by lagiordano** [learn-co-curriculum/react-hooks-event-handling-lab#7]
### Canvas Link

https://academyxi.instructure.com/courses/292/assignments/20308?module_item_id=41360

### Concern

There appears to be a rendering issue with this lab. The same error messages also appear when running tests. I've attached a screen shot of the error messages in the browser console below. 

Thanks!

### Additional Context

<img width="1091" alt="Screen Shot 2023-04-12 at 3 23 18 pm" src="https://user-images.githubusercontent.com/124640879/231359006-7b0b9620-afa8-45f5-bd22-4b1a88f8b619.png">

**Comment by lizbur10** [comment]
Hi @lagiordano ! For some of the React labs, you can expect errors like this if you haven't yet built the components. Take a look at the Note near the top of the readme for more details. If you have followed those instructions and are still getting these errors, the next step is to go to your instructor or to [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) to get help.

Good luck! 💙
